# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Peak.create(name: "Mt. Marcy", elevation: 5344, image: "mt_marcy.jpg", ascent: 3166)
Peak.create(name: "Algonquin Peak", elevation: 5114, image: "algonquin.jpg", ascent: 2936)
Peak.create(name: "Mt. Haystack", elevation: 4960, image: "mt_haystack.jpg", ascent: 3570)
Peak.create(name: "Mt. Skylight", elevation: 4926, image: "mt_skylight.jpg", ascent: 4265)
Peak.create(name: "Whiteface Mountain", elevation: 4867, image: "whiteface.jpg", ascent: 2535)
Peak.create(name: "Dix Mountain", elevation: 4857, image: "dix.jpg", ascent: 2800)
Peak.create(name: "Gray Peak", elevation: 4840, image: "gray_peak.jpg", ascent: 4178)
Peak.create(name: "Iroquois Peak", elevation: 4840, image: "iroquois_peak.jpg", ascent: 3250)
Peak.create(name: "Basin Mountain", elevation: 4827, image: "basin.jpg", ascent: 3650)
Peak.create(name: "Gothics", elevation: 4736, image: "gothics.jpg", ascent: 4070)
Peak.create(name: "Mt. Colden", elevation: 4714, image: "mt_colden.jpg", ascent: 2850)
Peak.create(name: "Giant Mountain", elevation: 4627, image: "giant.jpg", ascent: 3050)
Peak.create(name: "Nippletop", elevation: 4620, image: "nippletop.jpg", ascent: 4050)
Peak.create(name: "Santanoni Peak", elevation: 4607, image: "santanoni_peak.jpg", ascent: 2860)
Peak.create(name: "Mt. Redfield", elevation: 4606, image: "mt_redfield.jpg", ascent: 3225)
Peak.create(name: "Wright Peak", elevation: 4580, image: "wright_peak.jpg", ascent: 2400)
Peak.create(name: "Saddleback Mountain", elevation: 4515, image: "saddleback.jpg", ascent: 2990)
Peak.create(name: "Panther Peak", elevation: 4442, image: "panther_peak.jpg", ascent: 3762)
Peak.create(name: "Tabletop Mountain", elevation: 4427, image: "tabletop.jpg", ascent: 3660)
Peak.create(name: "Rocky Peak Ridge", elevation: 4420, image: "rocky_peak_ridge.jpg", ascent: 4500)
Peak.create(name: "Macomb Mountain", elevation: 4405, image: "macomb.jpg", ascent: 2344)
Peak.create(name: "Armstrong Mountain", elevation: 4400, image: "armstrong.jpg", ascent: 3734)
Peak.create(name: "Hough Peak", elevation: 4400, image: "hough_peak.jpg", ascent: 3200)
Peak.create(name: "Seward Mountain", elevation: 4361, image: "seward.jpg", ascent: 3490)
Peak.create(name: "Mt. Marshall", elevation: 4360, image: "mt_marshall.jpg", ascent: 2575)
Peak.create(name: "Allen Mountain", elevation: 4340, image: "allen.jpg", ascent: 2540)
Peak.create(name: "Big Slide Mountain", elevation: 4240, image: "big_slide.jpg", ascent: 2800)
Peak.create(name: "Esther Mountain", elevation: 4240, image: "esther.jpg", ascent: 3020)
Peak.create(name: "Upper Wolfjaw", elevation: 4185, image: "upper_wolfjaw.jpg", ascent: 3619)
Peak.create(name: "Lower Wolfjaw", elevation: 4175, image: "lower_wolfjaw.jpg", ascent: 2825)
Peak.create(name: "Street Mountain", elevation: 4166, image: "street.jpg", ascent: 2115)
Peak.create(name: "Phelps Mountain", elevation: 4161, image: "phelps.jpg", ascent: 3394)
Peak.create(name: "Mt. Donaldson", elevation: 4140, image: "mt_donaldson.jpg", ascent: 3490)
Peak.create(name: "Seymour Mountain", elevation: 4120, image: "seymour.jpg", ascent: 2370)
Peak.create(name: "Sawteeth", elevation: 4100, image: "sawteeth.jpg", ascent: 2975)
Peak.create(name: "Cascade Mountain", elevation: 4098, image: "cascade.jpg", ascent: 1940)
Peak.create(name: "South Dix", elevation: 4060, image: "south_dix.jpg", ascent: 3050)
Peak.create(name: "Porter Mountain", elevation: 4059, image: "porter.jpg", ascent: 2700)
Peak.create(name: "Mt. Colvin", elevation: 4057, image: "mt_colvin.jpg", ascent: 2130)
Peak.create(name: "Mt. Emmons", elevation: 4040, image: "mt_emmons.jpg", ascent: 3490)
Peak.create(name: "Dial Mountain", elevation: 4020, image: "dial.jpg", ascent: 3450)
Peak.create(name: "Grace Peak", elevation: 4012, image: "grace_peak.jpg", ascent: 3002)
Peak.create(name: "Blake", elevation: 3960, image: "blake.jpg", ascent: 3270)
Peak.create(name: "Cliff Mountain", elevation: 3960, image: "cliff.jpg", ascent: 2160)
Peak.create(name: "Nye Mountain", elevation: 3895, image: "nye.jpg", ascent: 1844)
Peak.create(name: "Couchsachraga Peak", elevation: 3820, image: "couchsachraga.jpg", ascent: 3140)
